heat_template_version: 2013-05-23

description: AWS SecurityGroup with Nova-Network opening single port.

parameters:
  port:
    type: string
    description: Port number to open
    default: '22'
  describe:
    type: string
    description: Description of the security group
    default: Test AWS SecGroup Nova-Network

resources:
  SecurityGroup:
    type: AWS::EC2::SecurityGroup
    properties:
      GroupDescription: { get_param: describe }
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/24'
        FromPort: { get_param: port }
        ToPort: { get_param: port }
        IpProtocol: 'tcp'
