heat_template_version: 2013-05-23

parameters:
  console_type:
    type: string
    default: novnc

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: TestVM
      flavor: m1.nano

outputs:
  console:
    description: Console for server
    value:
      get_attr:
      - server
      - console_urls
      #- get_param: console_type
