#!/usr/bin/env sh
cmd=${1:-"/bin/bash"}
client_pod=$(kubectl -n openstack get pod -l application=keystone,component=client -oname)
kubectl -n openstack exec -ti -c keystone-client $client_pod -- ${cmd}
