#!/usr/bin/env sh
if [ -n "$1" ]; then
    case $1 in
        *[!0-9]*) echo "if given, need an integer index for the mariadb-server-N pod"; exit 1 ;;
        *) pod="mariadb-server-$1" ;;
    esac
else
    echo "Discovering mariadb leader pod ..."
    pod=$(kubectl -n openstack get configmap openstack-mariadb-mariadb-state -ogo-template='{{index .metadata.annotations "openstackhelm.openstack.org/leader.node" }}')
fi
echo "Execing into openstack/$pod ..."
# shellcheck disable=SC2016 # these are to expand in container, not here
kubectl -n openstack exec -it "$pod"  -c mariadb -- \
    bash -c '[ -f /usr/bin/mariadb ] && cmd="/usr/bin/mariadb" || cmd="mysql"; $cmd -u${MYSQL_DBADMIN_USERNAME} -p${MYSQL_DBADMIN_PASSWORD}'
