#!/usr/bin/env bash

function usage {
    echo "Usage: $(basename $0) [-qh]" 2>&1
    echo "Wait for the OpenStackDeployment resource to become APPLIED"
    echo "expects single OpenStackDeployment[Status] resource in the 'openstack' namespace"
    echo "  -t <INT> polling interval in seconds, defaults to 10"
    echo "  -q       quiet, do not print visual confirmation of work"
    echo "  -h       print this message and exit"
}

POLL_TIMEOUT=10
QUIET=0

while getopts ':qh' arg; do
    case "${arg}" in
        q) QUIET=1;;
        t) POLL_TIMEOUT="${OPTARG}";;
        h) usage; exit 0;;
        ?) usage; exit 1;;
    esac
done

osdplst=$(kubectl -n openstack get osdplst --no-headers | awk '{print $1}')
until [ "$(kubectl -n openstack get osdplst $osdplst -ojsonpath='{.status.osdpl.state}')" == "APPLIED" ]; do
    sleep $POLL_TIMEOUT;
    if [ $QUIET == 0 ]; then
        echo -n "."
    fi
done
