#!/usr/bin/env bash
function repo_check {
    pushd "$1" > /dev/null
    echo -e "\n======="
    echo "$1"

    echo -e "\nGit branches"
    git branch -v

    gstatus=$(git status --porcelain)
    if [[ ! -z $gstatus ]]; then
        echo "Git Status:"
        echo "$gstatus"
    fi
    gstashes=$(git stash list)
    if [[ ! -z $gstashes ]]; then
        echo -e "\nGit stashes"
        echo -e "$gstashes"
    fi
    popd > /dev/null
}

for d in $(ls -d ${PWD}/*/); do
    if [ -d "$d/.git" ]; then
        repo_check $d
    fi
done
