#!/usr/bin/env bash
function repo_check {
    echo -e "\n======="
    echo "$1"
    git_cmd="git -C $d"

    echo -e "\nGit branches"
    $git_cmd branch -v

    gstatus=$($git_cmd status --porcelain)
    if [[ ! -z $gstatus ]]; then
        echo "Git Status:"
        echo "$gstatus"
    fi
    gstashes=$($git_cmd stash list)
    if [[ ! -z $gstashes ]]; then
        echo -e "\nGit stashes"
        echo -e "$gstashes"
    fi
}

for d in $(ls -d ${PWD}/*/); do
    if [ -d "$d/.git" ]; then
        repo_check $d
    fi
done
