heat_template_version: 2013-05-23

description: >
  Heat 2 x Tomcat behind HTTP Neutron load balancer + PostgreSQL

parameters:
  key_name:
    type: string
    description: SSH key to inject into instances
    default: mykey
  image:
    type: string
    description: Image to boot instances from
    default: cirros-0.3.1-x86_64-disk
  flavor:
    type: string
    description: Flavor of the created images
    default: m1.nano
  external_network:
    type: string
    description: Network of floating IPs
    default: 5a34e787-a75e-4e71-857c-01fe29e5437f
 
resources:

  #DbWaitHandle: 
    #type: AWS::CloudFormation::WaitConditionHandle
  
  #DbWaitCondition:
    #type: AWS::CloudFormation::WaitCondition
    #depends_on: DatabaseServer
    #properties:
      #Handle: { get_resource: DbWaitHandle }
      #Count: 1
      #Timeout: 600

  ApplicationServerOne:
    type: OS::Nova::Server
    #depends_on: { get_resource: DbWaitCondition }
    properties:
      availability_zone: nova
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - { port: { get_resource: PortAppOne } }

  ApplicationServerTwo:
    type: OS::Nova::Server
    #depends_on: { get_resource: DbWaitCondition }
    properties:
      availability_zone: nova
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - { port: { get_resource: PortAppTwo } }

  DatabaseServer:
    type: OS::Nova::Server
    properties:
      availability_zone: nova
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
      - { port: { get_resource: PortDB } }

  Router:
    type: OS::Neutron::Router
    properties:
      value_specs:
        external_gateway_info:
          network_id: { get_param: external_network }
  
  Net:
    type: OS::Neutron::Net
    name: 'Demo-Net'

  Subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: Net }
      ip_version: 4
      cidr: '10.0.1.0/24'
      dns_nameservers:
      - '8.8.8.8'

  RouterInterface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: Router }
      subnet_id: { get_resource: Subnet }

  PortAppOne:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: Net }
      fixed_ips:
      - { subnet_id: { get_resource: Subnet } }
      security_groups:
      - { get_resource: SecGroup }

  PortAppTwo:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: Net }
      fixed_ips:
      - { subnet_id: { get_resource: Subnet } }
      security_groups:
      - { get_resource: SecGroup }

  PortDB:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: Net }
      fixed_ips:
      - { subnet_id: { get_resource: Subnet } }
      security_groups:
      - { get_resource: SecGroup }

  AppPool:
    type: OS::Neutron::Pool
    properties:
      lb_method: ROUND_ROBIN
      protocol: HTTP
      name: AppPool
      subnet_id: { get_resource: Subnet }
      vip:
        protocol_port: 8080
        name: AppPoolVIP

  AppLoadBalancer:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 8080
      pool_id: { get_resource: AppPool }
      members:
      - { get_resource: ApplicationServerOne }
      - { get_resource: ApplicationServerTwo }

  AppFloatingIP:
    type: OS::Neutron::FloatingIP
    depends_on: { get_resource: RouterInterface }
    properties:
      floating_network_id: { get_param: external_network }

  AppFloatingIPassoc:
    type: OS::Neutron::FloatingIPAssociation
    properties: 
      floatingip_id: { get_resource: AppFloatingIP }
      port_id:
        Fn::Select:
        - 'port_id'
        - Fn::GetAtt: [ 'AppPool', 'vip' ]
  
  SecGroup:
    type: AWS::EC2::SecurityGroup
    properties:
      GroupDescription: Heat Demo
      SecurityGroupIngress:
      - { CidrIp: '0.0.0.0/0',
          IpProtocol: 'tcp',
          FromPort: '22',
          ToPort: '22'}
      - { CidrIp: '0.0.0.0/0',
          IpProtocol: 'tcp',
          FromPort: '5432',
          ToPort: '5432'}
      - { CidrIp: '0.0.0.0/0',
          IpProtocol: 'tcp',
          FromPort: '8080',
          ToPort: '8080'}

outputs:
  ApplicationServerBalanced:
    description: URL for load-balanced application
    value:
      str_replace:
        template: 'http://loadbalancer:8080/hello/HelloWorld'
        params:
          loadbalancer: { get_attr: [AppFloatingIP, floating_ip_address] }
