heat_template_version: pike

description: >
  Simplest http server using netcat, reports 200 + hostname on any request.
  Mostly targeted for CirrOS (tested with 0.3.5, 0.3.6, 0.4.0, 0.5.1).

parameters:
  curl_cli:
    type: string
  port:
    type: number

resources:
  config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #! /bin/sh -v
            NC_PORT=$PORT
            $NC_WEB_SCRIPT
            $wc_notify -k --data-binary '{"status": "SUCCESS"}'
          params:
            $wc_notify: { get_param: curl_cli }
            $PORT: { get_param: port }
            $NC_WEB_SCRIPT: { get_file: ncweb.sh }

outputs:
  OS::stack_id:
    value: { get_resource: config }
