heat_template_version: pike

description: |
  Simplest webapp using Python3 or Python.

parameters:
  curl_cli:
    type: string
  port:
    type: number

resources:
  config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - echo  $(hostname) > index.html
          - str_replace:
              template: |
                #! /bin/bash -v
                if type python3; then
                    cmd="python3 -m http.server"
                elif type python; then
                    cmd="python -m SimpleHTTPServer"
                else
                    $wc_notify --data-binary '{"status": "FAILURE"}'
                fi
                $cmd $PORT &
                $wc_notify --data-binary '{"status": "SUCCESS"}'
              params:
                $PORT: { get_param: port }
                $wc_notify: { get_param: curl_cli }
outputs:
  OS::stack_id:
    value: { get_resource: config }
