heat_template_version: pike

description: |
  Test server with WebApp on it.
  Actual webapp is defined in environment as Test::Web::App resource.

parameters:
  key:
    type: string
  flavor:
   type: string
  image:
    type: string
  app_port:
    type: number
    default: 80
  cidr:
    type: string
    default: 192.168.0.0/24
  public_net:
    type: string
    default: public

resources:

  net:
    type: OS::Neutron::Net

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: net }
      cidr: { get_param: cidr }

  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_max: { get_param: app_port }
          port_range_min: { get_param: app_port }
          remote_ip_prefix: '0.0.0.0/0'
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_max: 22
          port_range_min: 22
          remote_ip_prefix: '0.0.0.0/0'

  port:
    type: OS::Neutron::Port
    properties:
      replacement_policy: AUTO
      network: { get_resource: net }
      fixed_ips:
        - subnet: {get_resource: subnet }
      security_groups:
        - { get_resource: secgroup }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router_iface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  fip:
    type: OS::Neutron::FloatingIP
    depends_on: router_iface
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: port }

  config:
    type: Test::Web::App
    properties:
      curl_cli: { get_attr: [handle, curl_cli] }
      port: { get_param: app_port }

  server:
    type: OS::Nova::Server
    depends_on: router_iface
    properties:
      key_name: { get_param: key }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data: { get_resource: config }

  handle:
    type: OS::Heat::WaitConditionHandle

  waiter:
    type: OS::Heat::WaitCondition
    depends_on: server
    properties:
      count: 1
      timeout: 600
      handle: { get_resource: handle }

conditions:
  default_http_port:
    equals:
      - get_param: app_port
      - 80

outputs:
  fip:
    description: floating IP of the instance
    value: { get_attr: [fip, floating_ip_address] }
  url:
    description: URL of the webapp
    value:
      str_replace:
        template: http://$SERVER_IP$PORT
        params:
          $SERVER_IP: { get_attr: [ fip, floating_ip_address] }
          $PORT:
            if:
            - default_http_port
            - ""
            - str_replace:
                template: ":$port"
                params:
                  $port: { get_param: app_port }
