heat_template_version: 2015-10-15

description: |
  Simplest web-app using netcat reporting only hostname.
  Specifically tailored for minimal Cirros image.
  Also creates a script to create/release CPU load on instances.
  Execute these commands on the instance via SSH:
  "cpuload" to load all CPU cores,
  "cpuload -r" to release the CPU load,
  "cpuload -s" to show status of CPU load (on/off),
  "cpuload -i" to identify the host by hostname.

parameters:

  app_port:
    type: number

  wc_curl_cli:
    type: string

resources:

  webapp_nc:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #! /bin/sh -v
            echo 'SCRIPT' > /bin/cpuload
            chmod 777 /bin/cpuload
            Body=$(hostname)
            Response="HTTP/1.1 200 OK\r\nContent-Length: ${#Body}\r\n\r\n$Body"
            wc_notify --data-binary '{"status": "SUCCESS"}'
            while true ; do echo -e $Response | nc -llp PORT; done
          params:
            SCRIPT: {get_file: "https://raw.githubusercontent.com/pshchelo/stackdev/master/scripts/cpuload"}
            PORT: { get_param: app_port }
            wc_notify: { get_param: wc_curl_cli }

outputs:
  OS::stack_id:
    value: { get_resource: webapp_nc }
