#!/usr/bin/env bash
set -o pipefail
namespace=$1
secret=$2
field=$3

if [ -z $field ]; then
    kubectl -n ${namespace} get secret ${secret} -ojson | jq '.data | map_values(@base64d)'
else
    kubectl -n ${namespace} get secret ${secret} -ojson | jq -r --arg FLD "${field}" '.data[$FLD] | @base64d'
fi
