#!/usr/bin/env bash
default_args="-c osdpl"
set -x
kubectl -n osh-system get deploy -oname | grep -q 'rockoon$' && appname="rockoon" || appname="openstack-operator"
kubectl -n osh-system logs -l "app.kubernetes.io/instance=openstack-operator,app.kubernetes.io/name=$appname" ${@:-$default_args}
