#! /bin/sh
PID_FILE=/tmp/cpuload.pid
HOSTNAME=$(hostname)

set_status() {
    if [ -f "$PID_FILE" ]; then
        inprogress=true
    else
        inprogress=false
    fi
}

print_status() {
    local _load_on=$1
    if $_load_on; then
        echo "${HOSTNAME} - CPU load in progress"
    else
        echo "${HOSTNAME} - CPU load is not running"
    fi
}

cpu_load() {
    set_status
    if $inprogress; then
        print_status $inprogress
        exit 1
    else
        NUM_CPU=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu)
        echo "${HOSTNAME} - Starting CPU load"
        for in in $( seq $NUM_CPU ); do
            cat /dev/urandom >> /dev/null 2>&1 &
            echo $! >> $PID_FILE
        done
        exit 0
    fi
}

cpu_release() {
    set_status
    if $inprogress; then
        echo "${HOSTNAME} - Releasing CPU load"
        cat $PID_FILE | xargs kill
        rm -f $PID_FILE
        exit 0
    else
        print_status $inprogress
        exit 1
    fi
}

case $1 in
    -s | --status)
        set_status
        print_status $inprogress
    ;;
    -r | --release)
        cpu_release 
    ;;
    -i | --identify)
        echo ${HOSTNAME}
    ;;
    -h | --help)
        echo "cpuload [-r,--release|-i,--identify|-s,--status|-h,--help]"
        echo "        without arguments starts CPU load"
        echo "        --release   stop CPU load if running"
        echo "        --status    report if CPU load is in progress"
        echo "        --identify  print hostname"
        echo "        --help      pring this message"
        echo "        exit code: 1 if releasing unstarted load"
        echo "                     if starting already started load"

    ;;
    *)
        cpu_load
    ;;
esac
