heat_template_version: '2014-10-16'

description: |
  Simplest webapp using Python.

parameters:
  flavor:
   type: string
   default: m1.heat
  image:
    type: string
    default: fedora-heat-test-image
  port:
    type: number
    default: 80

resources:

  server_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - echo  $(hostname) > index.html
          - str_replace:
              template: |
                #! /bin/bash -v
                python -m SimpleHTTPServer PORT &
                wc_notify --data-binary '{"status": "SUCCESS"}'
              params:
                PORT: { get_param: port }
                wc_notify: { get_attr: [ handle, curl_cli ] }

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: RAW
      user_data: { get_resource: server_config }

  handle:
    type: OS::Heat::WaitConditionHandle

  waiter:
    type: OS::Heat::WaitCondition
    depends_on: server
    properties:
      count: 1
      timeout: 600
      handle: { get_resource: handle }
