#! /usr/bin/env sh
. /home/pshchelo/devstack/accrc/admin/admin
#imgloc="--file /home/pshchelo/devstack/files/Fedora-x86_64-20-20140618-sda.qcow2"
imgloc="--location http://archive.fedoraproject.org/pub/alt/openstack/20/x86_64/Fedora-x86_64-20-20140618-sda.qcow2"
glance image-create --progress --name F20-x86_64-cfntools --disk-format qcow2 --container-format bare --is-public True $imgloc
