#! /usr/bin/env sh
. $HOME/devstack/accrc/admin/admin
cirros="http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img"
glance image-create --progress --name TestVM --disk-format qcow2 --container-format bare --is-public True --location $cirros
