#! /usr/bin/env sh
# Use virt-customize to build AWS LOadbalancer image
PKGS="haproxy,socat,cronie,python-psutil"
cp "$1" "$1.orig"
virt-customize -a $1 --update --install $PKGS
virt-customize -a $1 --selinux-relabel --no-network
