#!/usr/bin/env bash
set -e
script_dir=$(dirname "$0")
ATTACH_NETWORK=1
CREATE_FIP=0
DEFAULT_FIP_POOL="public"
USE_CONFIG_DRIVE=0

__usage="
Usage: $(basename "$0") [-hv] [-n NAME] [-i IMAGE] [-f FLAVOR] [-a] [-p NET] [-c]
Relies on proper entry in clouds.yaml set via OS_CLOUD env var.

Requires the project in use to have a network with the same name as project.
Depending on a networking backend, this network must be connected to the
relevant floating network via a router when asking for accessible server.

If project has a security group with the same name as project, it will be used.
If user has a keypair with the same name as a project, it will be used.

Parameters:
    -n NAME   name of the server to create, default is autogenerated test-<random-number>
    -i IMAGE  image to use for the server (defaults to discover a cirros qcow2 image)
    -f FLAVOR flavor to use for the server (defaults discovered minimal available flavor suitable for a cirros image)
    -c        explicitly ask for config drive
    -a        make server accessible, create or pick existing floating IP and assigns to the server
    -p NET    name of the network to allocate floating IP from, defaults to '$DEFAULT_FIP_POOL'
    -A        create inaccessible server, w/o any network interfaces
    -H        host to create server on, only available to admins
    -z        availability zone to create server in
    -V        compute API microversion to use for create server request
    -v        be verbose (set -x)
    -h        show this message and exit
"

FIP_POOL=$DEFAULT_FIP_POOL
while getopts ':hvcaAV:H:z:p:n:i:f:' arg; do
    case "${arg}" in
        n) server_name="${OPTARG}";;
        i) server_image="${OPTARG}";;
        f) server_flavor="${OPTARG}";;
        z) server_az="${OPTARG}";;
        H) server_host="${OPTARG}";;
        A) ATTACH_NETWORK=0;;
        a) CREATE_FIP=1;;
        p) FIP_POOL="${OPTARG}";;
        c) USE_CONFIG_DRIVE=1;;
        V) api_version="${OPTARG}";;
        v) set -x ;;
        h) echo "$__usage"; exit 0 ;;
        *) echo "$__usage"; exit 1 ;;
    esac
done

RED='\033[0;31m'
GREEN='\033[0;32m'
NOC='\033[0m'
# shellcheck disable=SC2068 # passing all the args to echo verbatim
function errcho {
    >&2 echo $@;
}
function errcho_nice {
    errcho -e "${GREEN}""$1""${NOC}"
}
function errcho_fail {
    errcho -e "${RED}""$1""${NOC}"
}

project=$(openstack configuration show -f value -c auth.project_name)
optional_args=""

if [ "$USE_CONFIG_DRIVE" == "1" ]; then
    optional_args+=" --use-config-drive"
fi

if [ "$ATTACH_NETWORK" == "1" ]; then

    if openstack network show "$project" > /dev/null 2>&1; then
        errcho_nice "Using network $project"
        optional_args+=" --network $project"
    else
        errcho_fail "Can't find network named $project, abort."
        exit 1
    fi
else
    optional_args+=" --no-network"
fi

if [ -z "$server_name" ]; then
    # NOTE: $RANDOM is a 15-bit integer (0 - 32767)
    server_name="test-$(printf '%05d' $RANDOM)"
fi

if [ -z "$server_image" ]; then
    for im in $(openstack image list -f value -c ID -c Name | grep -i cirros); do
        # split on first space using shell parameter expansion (bash-specific)
        image_id="${im%% *}" # deletes longest substring that matches ' *' from the end
        image_name="${im#* }" # deletes shortest substring that matches '* ' from the start
        if [ "$(openstack image show "$image_id" -f value -c disk_format)" = "qcow2" ]; then
            server_image=$image_name
            break
        fi
    done
    if [ -z "$server_image" ]; then
        errcho_fail 'could not find suitable image to use, provide image with -i'
        exit 1
    else
        errcho_nice "Using image $server_image"
    fi
fi

if [ -z "$server_flavor" ]; then
    server_flavor=$(openstack flavor list --min-ram 128 --min-disk 1 --sort-column RAM --sort-ascending -f value -c Name | head -n1)
    if [ -z "$server_flavor" ]; then
        errcho_fail 'could not find a suitable flavor to use, provide flavor with -f'
    else
        errcho_nice "Using flavor $server_flavor"
    fi
fi

if [ "$ATTACH_NETWORK" == "1" ]; then
    if openstack security group show "$project" > /dev/null 2>&1; then
        optional_args+=" --security-group $project "
        errcho_nice "Using security group $project"
    fi
    if openstack keypair show "$project" > /dev/null 2>&1; then
        optional_args+=" --key-name $project "
        errcho_nice "Using keypair $project"
    fi
fi
if [ -n "$server_az" ]; then
    optional_args+=" --availability-zone $server_az"
fi
if [ -n "$server_host" ]; then
    optional_args+=" --host $server_host"
fi

# figure out proper api version if not specified
if [ -z "$api_version" ]; then
    if [ "$ATTACH_NETWORK" == "0" ]; then
        api_version="2.37"
    fi
    if [ -n "$server_host" ]; then
        api_version="2.74"
    fi
fi
if [ -n "$api_version" ]; then
    optional_args+=" --os-compute-api-version $api_version"
fi

# NOTE: assigning result of --wait needs openstack cli >= 8.2.0
# shellcheck disable=SC2086 # word splitting in optional_args is intentional
server_id=$(openstack server create "$server_name" \
    --image "$server_image" \
    --flavor "$server_flavor" \
    --user-data "$script_dir/cirros-http-cpuload.userdata" \
    $optional_args \
    -f value -c id \
    --wait
)
if [ -z "$server_id" ]; then
    errcho_fail "Failed to create server $server_name"
    openstack server show "$server_name"
    exit 1
fi

echo -n "$server_id" "$server_name"

if [ "$CREATE_FIP" == "0" ]; then
    echo
    exit 0
fi

# NOTE: admin sees all FIPs by default, but non-admin always get empty FIP list
# when listing with project, even with their own, so need to differentiate
project_filter=""
if [ "$project" = "admin" ]; then
    project_filter="--project admin"
fi

# shellcheck disable=SC2086 # word splitting in project_filter is intentional
fip=$(openstack floating ip list $project_filter --status DOWN -f value -c 'Floating IP Address' | sort -R | head -n1)
if [ -z "$fip" ]; then
    fip=$(openstack floating ip create "$FIP_POOL" -f value -c floating_ip_address)
fi
openstack server add floating ip "$server_id" "$fip"
echo " $fip"
