#!/usr/bin/env sh
#service openstack-heat-engine restart
crm resource restart p_openstack-heat-engine
service openstack-heat-api restart
service openstack-heat-api-cfn restart
service openstack-heat-api-cloudwatch restart
