heat_template_version: ocata

parameters:
  key_name:
    type: string
    default: demo
  flavor:
    type: string
    default: m1.nano
  image:
    type: string
    default: cirros-0.3.5-x86_64-disk
  net:
    type: string
  subnet:
    type: string
  secgroup:
    type: string
  public_net:
    type: string
    default: public

resources:

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: net }
      fixed_ips:
        - subnet: { get_param: subnet }
      security_groups:
        - { get_param: secgroup }

  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: port }

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port }

outputs:
  fip:
    value: { get_attr: [ fip, floating_ip_address ] }
